<?php
// "taskName" => "Array task",
// "importantTask" => true,
// "taskText" => "First task text",
// "deadline" => [],
// "taskResult" => true,
// "project" => "main array",
// "timeTracking" => true,
// "remindAboutTask" => [],
// "repeatTask" => true,
// "CRM" => ["1", "1", "1", "1"],
// "makeSubtask" => "Скачать приложение Битрикс24",
// "tags" => ["1", "1", "1", "1"],
// "relatedTasks" => ["Скачать приложение Битрикс24", "Скачать приложение Битрикс24", "Скачать приложение Битрикс24", "Скачать приложение Битрикс24"],

// "taskName" => "",
// "importantTask" => "",
// "taskText" => "",
// "deadline" => "",
// "taskResult" => "",
// "project" => "",
// "timeTracking" => "",
// "remindAboutTask" => [],
// "repeatTask" => "",
// "CRM" => [],
// "makeSubtask" => "",
// "tags" => [],
// "relatedTasks" => [],

// "taskName": "JSON task",
// "importantTask": false,
// "taskText": "Second task text",
// "deadline": [],
// "taskResult": false,
// "project": "main json",
// "timeTracking": false,
// "remindAboutTask": [],
// "repeatTask": false,
// "CRM": ["2", "2", "2", "2"],
// "makeSubtask": "Удалить приложение Битрикс24",
// "tags": ["2", "2", "2", "2"],
// "relatedTasks": ["Удалить приложение Битрикс24", "Удалить приложение Битрикс24", "Удалить приложение Битрикс24", "Удалить приложение Битрикс24"]

// "taskName": "",
// "importantTask": "",
// "taskText": "",
// "deadline": "",
// "taskResult": "",
// "project": "",
// "timeTracking": "",
// "remindAboutTask": [],
// "repeatTask": "",
// "CRM": [],
// "makeSubtask": "",
// "tags": [],
// "relatedTasks": []